# Scarping Websites

# First Data

In [90]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import csv

In [91]:
page = requests.get("https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)")
src = page.content
soup = BeautifulSoup(src, 'html.parser')
print(soup)

<!DOCTYPE html>

<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>List of countries by population (United Nations) - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy",
"wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"75acbab1-f72a-49aa-88ec-b52fd6073694","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_countries_by_population_(United_Nations)","wgTitle":"List of countries by population (United Nations)","wgCurRevisionId":1276983731,"wgRevisionId":1276983731,"wgArticleId":39707994,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Pages where node count is exceeded","Lists of countries by past and future population (United Nations)","Lists of countries by continent"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_countries_by_population_(United_Nations)","wgRelevantArticleId":39707994,
"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgCiteReferencePreviewsActive":false,"wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":80000,"wgEditSubmitButtonLabelPublish":true,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q66084740","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGETopicsMatchModeEnabled":
false,"wgGEStructuredTaskRejectionReasonTextInputEnabled":false,"wgGELevelingUpEnabledForUser":false};RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","ext.wikimediamessages.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wikimediaBadges":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","mediawiki.page.media","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar",
"ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","ext.checkUser.clientHints","ext.growthExperiments.SuggestedEditSession"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.44.0-wmf.17" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/United_Nations_geographical_subregions.png/1200px-United_Nations_geographical_subregions.png" property="og:image"/>
<meta content="1200" property="og:image:width"/>
<meta content="555" property="og:image:height"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/United_Nations_geographical_subregions.png/800px-United_Nations_geographical_subregions.png" property="og:image"/>
<meta content="800" property="og:image:width"/>
<meta content="370" property="og:image:height"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/United_Nations_geographical_subregions.png/640px-United_Nations_geographical_subregions.png" property="og:image"/>
<meta content="640" property="og:image:width"/>
<meta content="296" property="og:image:height"/>
<meta content="width=1120" name="viewport"/>
<meta content="List of countries by population (United Nations) - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="//en.m.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)" media="only screen and (max-width: 640px)" rel="alternate"/>
<link href="/w/index.php?title=List_of_countries_by_population_(United_Nations)&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch">
<link href="login.wikimedia.org" rel="dns-prefetch"/>
</link></head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_countries_by_population_United_Nations rootpage-List_of_countries_by_population_United_Nations skin-vector-2022 action-view"><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a href="/wiki/Special:SpecialPages"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/wikipedia.png" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="13" src="/static/images/mobile/copyright/wikipedia-tagline-en.svg" style="width: 7.3125em; height: 0.8125em;" width="117"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="sentences" class="cdx-text-input__input" id="searchInput" name="search" placeholder="Search Wikipedia" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-sitesupport-2"><a class="" data-mw="interface" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw="interface" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+countries+by+population+%28United+Nations%29" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw="interface" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+countries+by+population+%28United+Nations%29" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item" id="pt-sitesupport"><a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-createaccount"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+countries+by+population+%28United+Nations%29" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-login"><a accesskey="o" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+countries+by+population+%28United+Nations%29" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-user-menu-anon-editor" id="p-user-menu-anon-editor">
<div class="vector-menu-heading">

In [92]:
table = soup.find('table', {'class': 'wikitable'})
print(table)

<table class="wikitable sortable mw-datatable sticky-header static-row-numbers sort-under col1left col5left col6left" style="text-align:right">
<caption>List of countries and inhabited territories by total population. United Nations
</caption>
<tbody><tr>
<th>Country or territory
</th>
<th>Population<br/>(1 July 2022)
</th>
<th>Population<br/>(1 July 2023)
</th>
<th>Change<br/>(%)
</th>
<th style="max-width:9em;"><a href="/wiki/United_Nations_geoscheme" title="United Nations geoscheme">UN continental<br/>region</a><sup class="reference" id="cite_ref-UNregions_1-1"><a href="#cite_note-UNregions-1"><span class="cite-bracket">[</span>1<span class="cite-bracket">]</span></a></sup>
</th>
<th style="max-width:8em;"><a href="/wiki/List_of_countries_and_territories_by_the_United_Nations_geoscheme" title="List of countries and territories by the United Nations geoscheme">UN statistical<br/>subregion</a><sup class="reference" id="cite_ref-UNregions_1-2"><a href="#cite_note-UNregions-1"><span class="cite-bracket">[</span>1<span class="cite-bracket">]</span></a></sup>
</th></tr>
<tr class="static-row-numbers-norank">
<td><b><span class="flagicon" style="padding-left:25px;"> </span><a href="/wiki/World_population" title="World population">World</a></b></td>
<td>8,021,407,192</td>
<td>8,091,734,930</td>
<td><span data-sort-value="6999880000000000000♠" style="display:none"></span><span style="color:green">+0.88%</span></td>
<td>–</td>
<td>–
</td></tr>
<tr>
<td><span data-sort-value="India"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/35px-Flag_of_India.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/45px-Flag_of_India.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/India" title="India">India</a></span></td>
<td>1,425,423,212</td>
<td>1,438,069,596</td>
<td><span data-sort-value="6999890000000000000♠" style="display:none"></span><span style="color:green">+0.89%</span></td>
<td><a href="/wiki/Asia" title="Asia">Asia</a></td>
<td><a href="/wiki/South_Asia" title="South Asia">Southern Asia</a>
</td></tr>
<tr>
<td><span data-sort-value="China"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/China" title="China">China</a></span><sup class="reference" id="cite_ref-3"><a href="#cite_note-3"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a></sup></td>
<td>1,425,179,569</td>
<td>1,422,584,933</td>
<td><span data-sort-value="3000820000000000000♠" style="display:none"></span><span style="color:red">−0.18%</span></td>
<td><a href="/wiki/Asia" title="Asia">Asia</a></td>
<td><a href="/wiki/East_Asia" title="East Asia">Eastern Asia</a>
</td></tr>
<tr>
<td><span data-sort-value="United States"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/United_States" title="United States">United States</a></span></td>
<td>341,534,046</td>
<td>343,477,335</td>
<td><span data-sort-value="6999570000000000000♠" style="display:none"></span><span style="color:green">+0.57%</span></td>
<td><a href="/wiki/Americas" title="Americas">Americas</a></td>
<td><a href="/wiki/Northern_America" title="Northern America">Northern America</a>
</td></tr>
<tr>
<td><span data-sort-value="Indonesia"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/23px-Flag_of_Indonesia.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/35px-Flag_of_Indonesia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/45px-Flag_of_Indonesia.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Indonesia" title="Indonesia">Indonesia</a></span></td>
<td>278,830,529</td>
<td>281,190,067</td>
<td><span data-sort-value="6999850000000000000♠" style="display:none"></span><span style="color:green">+0.85%</span></td>
<td><a href="/wiki/Asia" title="Asia">Asia</a></td>
<td><a href="/wiki/Southeast_Asia" title="Southeast Asia">South-eastern Asia</a>
</td></tr>
<tr>
<td><span data-sort-value="Pakistan"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/23px-Flag_of_Pakistan.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/35px-Flag_of_Pakistan.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/45px-Flag_of_Pakistan.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Pakistan" title="Pakistan">Pakistan</a></span></td>
<td>243,700,667</td>
<td>247,504,495</td>
<td><span data-sort-value="7000156000000000000♠" style="display:none"></span><span style="color:green">+1.56%</span></td>
<td><a href="/wiki/Asia" title="Asia">Asia</a></td>
<td><a href="/wiki/South_Asia" title="South Asia">Southern Asia</a>
</td></tr>
<tr>
<td><span data-sort-value="Nigeria"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/23px-Flag_of_Nigeria.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/35px-Flag_of_Nigeria.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/46px-Flag_of_Nigeria.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Nigeria" title="Nigeria">Nigeria</a></span></td>
<td>223,150,896</td>
<td>227,882,945</td>
<td><span data-sort-value="7000212000000000000♠" style="display:none"></span><span style="color:green">+2.12%</span></td>
<td><a href="/wiki/Africa" title="Africa">Africa</a></td>
<td><a href="/wiki/West_Africa" title="West Africa">Western Africa</a>
</td></tr>
<tr>
<td><span data-sort-value="Brazil"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="700" data-file-width="1000" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/22px-Flag_of_Brazil.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/33px-Flag_of_Brazil.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/43px-Flag_of_Brazil.svg.png 2x" width="22"/></span></span> </span><a href="/wiki/Brazil" title="Brazil">Brazil</a></span></td>
<td>210,306,415</td>
<td>211,140,729</td>
<td><span data-sort-value="6999400000000000000♠" style="display:none"></span><span style="color:green">+0.40%</span></td>
<td><a href="/wiki/Americas" title="Americas">Americas</a></td>
<td><a href="/wiki/South_America" title="South America">South America</a>
</td></tr>
<tr>
<td><span data-sort-value="Bangladesh"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="307" data-file-width="512" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/23px-Flag_of_Bangladesh.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/35px-Flag_of_Bangladesh.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/46px-Flag_of_Bangladesh.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Bangladesh" title="Bangladesh">Bangladesh</a></span></td>
<td>169,384,897</td>
<td>171,466,990</td>
<td><span data-sort-value="7000123000000000000♠" style="display:none"></span><span style="color:green">+1.23%</span></td>
<td><a href="/wiki/Asia" title="Asia">Asia</a></td>
<td><a href="/wiki/South_Asia" title="South Asia">Southern Asia</a>
</td></tr>
<tr>
<td><span data-sort-value="Russia"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/23px-Flag_of_Russia.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/35px-Flag_of_Russia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/45px-Flag_of_Russia.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Russia" title="Russia">Russia</a></span></td>
<td>145,579,899</td>
<td>145,440,500</td>
<td><span data-sort-value="3000900000000000000♠" style="display:none"></span><span style="color:red">−0.10%</span></td>
<td><a href="/wiki/Europe" title="Europe">Europe</a></td>
<td><a href="/wiki/Eastern_Europe" title="Eastern Europe">Eastern Europe</a>
</td></tr>
<tr>
<td><span data-sort-value="Mexico"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="560" data-file-width="980" decoding="async" height="13" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/23px-Flag_of_Mexico.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/35px-Flag_of_Mexico.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/46px-Flag_of_Mexico.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Mexico" title="Mexico">Mexico</a></span></td>
<td>128,613,117</td>
<td>129,739,759</td>
<td><span data-sort-value="6999880000000000000♠" style="display:none"></span><span style="color:green">+0.88%</span></td>
<td><a href="/wiki/Americas" title="Americas">Americas</a></td>
<td><a href="/wiki/Central_America" title="Central America">Central America</a>
</td></tr>
<tr>
<td><span data-sort-value="Ethiopia"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/23px-Flag_of_Ethiopia.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/35px-Flag_of_Ethiopia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/46px-Flag_of_Ethiopia.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Ethiopia" title="Ethiopia">Ethiopia</a></span></td>
<td>125,384,287</td>
<td>128,691,692</td>
<td><span data-sort-value="7000264000000000000♠" style="display:none"></span><span style="color:green">+2.64%</span></td>
<td><a href="/wiki/Africa" title="Africa">Africa</a></td>
<td><a href="/wiki/East_Africa" title="East Africa">Eastern Africa</a>
</td></tr>
<tr>
<td><span data-sort-value="Japan"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/23px-Flag_of_Japan.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/35px-Flag_of_Japan.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/45px-Flag_of_Japan.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Japan" title="Japan">Japan</a></span></td>
<td>124,997,578</td>
<td>124,370,947</td>
<td><span data-sort-value="3000500000000000000♠" style="display:none"></span><span style="color:red">−0.50%</span></td>
<td><a href="/wiki/Asia" title="Asia">Asia</a></td>
<td><a href="/wiki/East_Asia" title="East Asia">Eastern Asia</a>
</td></tr>
<tr>
<td><span data-sort-value="Philippines"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/23px-Flag_of_the_Philippines.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/35px-Flag_of_the_Philippines.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/46px-Flag_of_the_Philippines.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Philippines" title="Philippines">Philippines</a></span></td>
<td>113,964,338</td>
<td>114,891,199</td>
<td><span data-sort-value="6999810000000000000♠" style="display:none"></span><span style="color:green">+0.81%</span></td>
<td><a href="/wiki/Asia" title="Asia">Asia</a></td>
<td><a href="/wiki/Southeast_Asia" title="Southeast Asia">South-eastern Asia</a>
</td></tr>
<tr>
<td><span data-sort-value="Egypt"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/23px-Flag_of_Egypt.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/35px-Flag_of_Egypt.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/45px-Flag_of_Egypt.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Egypt" title="Egypt">Egypt</a></span></td>
<td>112,618,250</td>
<td>114,535,772</td>
<td><span data-sort-value="7000170000000000000♠" style="display:none"></span><span style="color:green">+1.70%</span></td>
<td><a href="/wiki/Africa" title="Africa">Africa</a></td>
<td><a href="/wiki/North_Africa" title="North Africa">Northern Africa</a>
</td></tr>
<tr>
<td><span data-sort-value="DR Congo"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="800" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/20px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/31px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/40px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png 2x" width="20"/></span></span> </span><a href="/wiki/Democratic_Republic_of_the_Congo" title="Democratic Republic of the Congo">DR Congo</a></span></td>
<td>102,396,968</td>
<td>105,789,731</td>
<td><span data-sort-value="7000331000000000000♠" style="display:none"></span><span style="color:green">+3.31%</span></td>
<td><a href="/wiki/Africa" title="Africa">Africa</a></td>
<td><a href="/wiki/Central_Africa" title="Central Africa">Middle Africa</a>
</td></tr>
<tr>
<td><span data-sort-value="Vietnam"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/23px-Flag_of_Vietnam.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/35px-Flag_of_Vietnam.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/45px-Flag_of_Vietnam.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Vietnam" title="Vietnam">Vietnam</a></span></td>
<td>99,680,655</td>
<td>100,352,192</td>
<td><span data-sort-value="6999670000000000000♠" style="display:none"></span><span style="color:green">+0.67%</span></td>
<td><a href="/wiki/Asia" title="Asia">Asia</a></td>
<td><a href="/wiki/Southeast_Asia" title="Southeast Asia">South-eastern Asia</a>
</td></tr>
<tr>
<td><span data-sort-value="Iran"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="360" data-file-width="630" decoding="async" height="13" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/35px-Flag_of_Iran.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/46px-Flag_of_Iran.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Iran" title="Iran">Iran</a></span></td>
<td>89,524,246</td>
<td>90,608,707</td>
<td><span data-sort-value="7000121000000000000♠" style="display:none"></span><span style="color:green">+1.21%</span></td>
<td><a href="/wiki/Asia" title="Asia">Asia</a></td>
<td><a href="/wiki/South_Asia" title="South Asia">Southern Asia</a>
</td></tr>
<tr>
<td><span data-sort-value="Turkey"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="800" data-file-width="1200" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/23px-Flag_of_Turkey.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/35px-Flag_of_Turkey.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/45px-Flag_of_Turkey.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Turkey" title="Turkey">Turkey</a></span></td>
<td>87,058,473</td>
<td>87,270,501</td>
<td><span data-sort-value="6999240000000000000♠" style="display:none"></span><span style="color:green">+0.24%</span></td>
<td><a href="/wiki/Asia" title="Asia">Asia</a></td>
<td><a href="/wiki/West_Asia" title="West Asia">Western Asia</a>
</td></tr>
<tr>
<td><span data-sort-value="Germany"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="1000" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/23px-Flag_of_Germany.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/35px-Flag_of_Germany.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/46px-Flag_of_Germany.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Germany" title="Germany">Germany</a></span></td>
<td>84,086,227</td>
<td>84,548,231</td>
<td><span data-sort-value="6999550000000000000♠" style="display:none"></span><span style="color:green">+0.55%</span></td>

In [93]:
table_of_th = table.find_all('th')
print(table_of_th)

[<th>Country or territory
</th>, <th>Population<br/>(1 July 2022)
</th>, <th>Population<br/>(1 July 2023)
</th>, <th>Change<br/>(%)
</th>, <th style="max-width:9em;"><a href="/wiki/United_Nations_geoscheme" title="United Nations geoscheme">UN continental<br/>region</a><sup class="reference" id="cite_ref-UNregions_1-1"><a href="#cite_note-UNregions-1"><span class="cite-bracket">[</span>1<span class="cite-bracket">]</span></a></sup>
</th>, <th style="max-width:8em;"><a href="/wiki/List_of_countries_and_territories_by_the_United_Nations_geoscheme" title="List of countries and territories by the United Nations geoscheme">UN statistical<br/>subregion</a><sup class="reference" id="cite_ref-UNregions_1-2"><a href="#cite_note-UNregions-1"><span class="cite-bracket">[</span>1<span class="cite-bracket">]</span></a></sup>
</th>]

In [94]:
headers = []
for th in table_of_th :
    headers.append(th.text.strip())
print(headers)

['Country or territory', 'Population(1 July 2022)', 'Population(1 July 2023)', 'Change(%)', 'UN continentalregion[1]', 'UN statisticalsubregion[1]']

In [ ]:
rows = []
for row in table.find_all('tr')[1:]:  
    columns = row.find_all('td')
    if len(columns) > 1:  
        row_data = [col.text.strip() for col in columns]
        rows.append(row_data)
print(rows)

[['World', '8,021,407,192', '8,091,734,930', '+0.88%', '–', '–'], ['India', '1,425,423,212', '1,438,069,596', '+0.89%', 'Asia', 'Southern Asia'], ['China[a]', '1,425,179,569', '1,422,584,933', '−0.18%', 'Asia', 'Eastern Asia'], ['United States', '341,534,046', '343,477,335', '+0.57%', 'Americas', 'Northern America'], ['Indonesia', '278,830,529', '281,190,067', '+0.85%', 'Asia', 'South-eastern Asia'], ['Pakistan', '243,700,667', '247,504,495', '+1.56%', 'Asia', 'Southern Asia'], ['Nigeria', '223,150,896', '227,882,945', '+2.12%', 'Africa', 'Western Africa'], ['Brazil', '210,306,415', '211,140,729', '+0.40%', 'Americas', 'South America'], ['Bangladesh', '169,384,897', '171,466,990', '+1.23%', 'Asia', 'Southern Asia'], ['Russia', '145,579,899', '145,440,500', '−0.10%', 'Europe', 'Eastern Europe'], ['Mexico', '128,613,117', '129,739,759', '+0.88%', 'Americas', 'Central America'], ['Ethiopia', '125,384,287', '128,691,692', '+2.64%', 'Africa', 'Eastern Africa'], ['Japan', '124,997,578', '124,370,947', '−0.50%', 'Asia', 'Eastern Asia'], ['Philippines', '113,964,338', '114,891,199', '+0.81%', 'Asia', 'South-eastern Asia'], ['Egypt', '112,618,250', '114,535,772', '+1.70%', 'Africa', 'Northern Africa'], ['DR Congo', '102,396,968', '105,789,731', '+3.31%', 'Africa', 'Middle Africa'], ['Vietnam', '99,680,655', '100,352,192', '+0.67%', 'Asia', 'South-eastern Asia'], ['Iran', '89,524,246', '90,608,707', '+1.21%', 'Asia', 'Southern Asia'], ['Turkey', '87,058,473', '87,270,501', '+0.24%', 'Asia', 'Western Asia'], ['Germany', '84,086,227', '84,548,231', '+0.55%', 'Europe', 'Western Europe'], ['Thailand', '71,735,329', '71,702,435', '−0.05%', 'Asia', 'South-eastern Asia'], ['United Kingdom', '68,179,315', '68,682,962', '+0.74%', 'Europe', 'Northern Europe'], ['Tanzania[b]', '64,711,821', '66,617,606', '+2.95%', 'Africa', 'Eastern Africa'], ['France[c]', '66,277,409', '66,438,822', '+0.24%', 'Europe', 'Western Europe'], ['South Africa', '62,378,410', '63,212,384', '+1.34%', 'Africa', 'Southern Africa'], ['Italy', '59,619,115', '59,499,453', '−0.20%', 'Europe', 'Southern Europe'], ['Kenya', '54,252,461', '55,339,003', '+2.00%', 'Africa', 'Eastern Africa'], ['Myanmar', '53,756,787', '54,133,798', '+0.70%', 'Asia', 'South-eastern Asia'], ['Colombia', '51,737,944', '52,321,152', '+1.13%', 'Americas', 'South America'], ['South Korea', '51,782,512', '51,748,739', '−0.07%', 'Asia', 'Eastern Asia'], ['Sudan', '49,383,346', '50,042,791', '+1.34%', 'Africa', 'Northern Africa'], ['Uganda', '47,312,719', '48,656,601', '+2.84%', 'Africa', 'Eastern Africa'], ['Spain[d]', '47,828,382', '47,911,579', '+0.17%', 'Europe', 'Southern Europe'], ['Algeria', '45,477,389', '46,164,219', '+1.51%', 'Africa', 'Northern Africa'], ['Argentina', '45,407,904', '45,538,401', '+0.29%', 'Americas', 'South America'], ['Iraq', '44,070,551', '45,074,049', '+2.28%', 'Asia', 'Western Asia'], ['Afghanistan', '40,578,842', '41,454,761', '+2.16%', 'Asia', 'Southern Asia'], ['Yemen', '38,222,876', '39,390,799', '+3.06%', 'Asia', 'Western Asia'], ['Canada', '38,821,259', '39,299,105', '+1.23%', 'Americas', 'Northern America'], ['Poland', '38,385,739', '38,762,844', '+0.98%', 'Europe', 'Eastern Europe'], ['Ukraine[e]', '41,048,766', '37,732,836', '−8.08%', 'Europe', 'Eastern Europe'], ['Morocco', '37,329,064', '37,712,505', '+1.03%', 'Africa', 'Northern Africa'], ['Angola', '35,635,029', '36,749,906', '+3.13%', 'Africa', 'Middle Africa'], ['Uzbekistan', '34,938,955', '35,652,307', '+2.04%', 'Asia', 'Central Asia'], ['Malaysia', '34,695,493', '35,126,298', '+1.24%', 'Asia', 'South-eastern Asia'], ['Peru', '33,475,438', '33,845,617', '+1.11%', 'Americas', 'South America'], ['Ghana', '33,149,152', '33,787,914', '+1.93%', 'Africa', 'Western Africa'], ['Mozambique', '32,656,246', '33,635,160', '+3.00%', 'Africa', 'Eastern Africa'], ['Saudi Arabia', '32,175,352', '32,264,292', '+0.28%', 'Asia', 'Western Asia'], ['Madagascar', '30,437,261', '31,195,932', '+2.49%', 'Africa', 'Eastern Africa'], ['Ivory Coast', '30,395,002', '31,165,654', '+2.54%', 'Africa', 'Western Africa'], ['Nepal', '29,715,436', '29,964,614', '+0.84%', 'Asia', 'Southern Asia'], ['Cameroon', '27,632,771', '28,372,687', '+2.68%', 'Africa', 'Middle Africa'], ['Venezuela', '28,213,017', '28,300,854', '+0.31%', 'Americas', 'South America'], ['Australia[f]', '26,200,984', '26,451,124', '+0.95%', 'Oceania', 'Australia and New Zealand'], ['North Korea', '26,329,845', '26,418,204', '+0.34%', 'Asia', 'Eastern Asia'], ['Niger', '25,311,973', '26,159,867', '+3.35%', 'Africa', 'Western Africa'], ['Mali', '23,072,640', '23,769,127', '+3.02%', 'Africa', 'Western Africa'], ['Syria', '22,462,173', '23,594,623', '+5.04%', 'Asia', 'Western Asia'], ['Taiwan[g]', '23,420,111', '23,317,145', '−0.44%', 'Asia', 'Eastern Asia'], ['Burkina Faso', '22,509,038', '23,025,776', '+2.30%', 'Africa', 'Western Africa'], ['Sri Lanka', '22,834,965', '22,971,617', '+0.60%', 'Asia', 'Southern Asia'], ['Malawi', '20,568,728', '21,104,482', '+2.60%', 'Africa', 'Eastern Africa'], ['Zambia', '20,152,938', '20,723,965', '+2.83%', 'Africa', 'Eastern Africa'], ['Kazakhstan', '20,034,609', '20,330,104', '+1.47%', 'Asia', 'Central Asia'], ['Chile', '19,553,036', '19,658,835', '+0.54%', 'Americas', 'South America'], ['Chad', '18,455,316', '19,319,064', '+4.68%', 'Africa', 'Middle Africa'], ['Romania', '19,166,772', '19,118,479', '−0.25%', 'Europe', 'Eastern Europe'], ['Somalia[h]', '17,801,897', '18,358,615', '+3.13%', 'Africa', 'Eastern Africa'], ['Guatemala', '17,847,877', '18,124,838', '+1.55%', 'Americas', 'Central America'], ['Senegal', '17,651,103', '18,077,573', '+2.42%', 'Africa', 'Western Africa'], ['Netherlands[i]', '17,904,421', '18,092,524', '+1.05%', 'Europe', 'Western Europe'], ['Ecuador', '17,823,897', '17,980,083', '+0.88%', 'Americas', 'South America'], ['Cambodia', '17,201,724', '17,423,880', '+1.29%', 'Asia', 'South-eastern Asia'], ['Zimbabwe', '16,069,056', '16,340,822', '+1.69%', 'Africa', 'Eastern Africa'], ['Guinea', '14,055,137', '14,405,465', '+2.49%', 'Africa', 'Western Africa'], ['Benin', '13,759,501', '14,111,034', '+2.55%', 'Africa', 'Western Africa'], ['Rwanda', '13,651,030', '13,954,471', '+2.22%', 'Africa', 'Eastern Africa'], ['Burundi', '13,321,097', '13,689,450', '+2.77%', 'Africa', 'Eastern Africa'], ['Bolivia', '12,077,154', '12,244,159', '+1.38%', 'Americas', 'South America'], ['Tunisia', '12,119,334', '12,200,431', '+0.67%', 'Africa', 'Northern Africa'], ['Belgium', '11,641,820', '11,712,893', '+0.61%', 'Europe', 'Western Europe'], ['Haiti', '11,503,606', '11,637,398', '+1.16%', 'Americas', 'Caribbean'], ['South Sudan', '11,021,177', '11,483,374', '+4.19%', 'Africa', 'Eastern Africa'], ['Jordan', '11,256,263', '11,439,213', '+1.63%', 'Asia', 'Western Asia'], ['Dominican Republic', '11,230,734', '11,331,265', '+0.90%', 'Americas', 'Caribbean'], ['Cuba', '11,059,820', '11,019,931', '−0.36%', 'Americas', 'Caribbean'], ['Czechia', '10,673,213', '10,809,716', '+1.28%', 'Europe', 'Eastern Europe'], ['Honduras', '10,463,872', '10,644,851', '+1.73%', 'Americas', 'Central America'], ['United Arab Emirates', '10,242,086', '10,642,081', '+3.91%', 'Asia', 'Western Asia'], ['Sweden', '10,487,338', '10,551,494', '+0.61%', 'Europe', 'Northern Europe'], ['Portugal[j]', '10,417,073', '10,430,738', '+0.13%', 'Europe', 'Southern Europe'], ['Tajikistan', '10,182,222', '10,389,799', '+2.04%', 'Asia', 'Central Asia'], ['Papua New Guinea', '10,203,169', '10,389,635', '+1.83%', 'Oceania', 'Melanesia'], ['Azerbaijan', '10,295,304', '10,318,207', '+0.22%', 'Asia', 'Western Asia'], ['Greece', '10,412,480', '10,242,908', '−1.63%', 'Europe', 'Southern Europe'], ['Hungary', '9,964,306', '9,686,463', '−2.79%', 'Europe', 'Eastern Europe'], ['Togo', '9,089,738', '9,304,337', '+2.36%', 'Africa', 'Western Africa'], ['Israel', '9,103,151', '9,256,314', '+1.68%', 'Asia', 'Western Asia'], ['Austria', '9,064,677', '9,130,429', '+0.73%', 'Europe', 'Western Europe'], ['Belarus', '9,173,237', '9,115,680', '−0.63%', 'Europe', 'Eastern Europe'], ['Switzerland', '8,792,182', '8,870,561', '+0.89%', 'Europe', 'Western Europe'], ['Sierra Leone', '8,276,807', '8,460,512', '+2.22%', 'Africa', 'Western Africa'], ['Laos', '7,559,007', '7,664,993', '+1.40%', 'Asia', 'South-eastern Asia'], ['Hong Kong (China)[k]', '7,465,915', '7,442,734', '−0.31%', 'Asia', 'Eastern Asia'], ['Turkmenistan', '7,230,193', '7,364,438', '+1.86%', 'Asia', 'Central Asia'], ['Libya', '7,223,805', '7,305,659', '+1.13%', 'Africa', 'Northern Africa'], ['Kyrgyzstan', '6,955,788', '7,073,516', '+1.69%', 'Asia', 'Central Asia'], ['Paraguay', '6,760,464', '6,844,146', '+1.24%', 'Americas', 'South America'], ['Nicaragua', '6,730,654', '6,823,613', '+1.38%', 'Americas', 'Central America'], ['Bulgaria', '6,825,864', '6,795,803', '−0.44%', 'Europe', 'Eastern Europe'], ['Serbia[l]', '6,791,213', '6,773,201', '−0.27%', 'Europe', 'Southern Europe'], ['El Salvador', '6,280,319', '6,309,624', '+0.47%', 'Americas', 'Central America'], ['Congo', '6,035,104', '6,182,885', '+2.45%', 'Africa', 'Middle Africa'], ['Denmark', '5,902,904', '5,948,136', '+0.77%', 'Europe', 'Northern Europe'], ['Singapore', '5,649,885', '5,789,090', '+2.46%', 'Asia', 'South-eastern Asia'], ['Lebanon', '5,744,489', '5,733,493', '−0.19%', 'Asia', 'Western Asia'], ['Finland[m]', '5,569,299', '5,601,185', '+0.57%', 'Europe', 'Northern Europe'], ['Norway[n]', '5,457,801', '5,519,167', '+1.12%', 'Europe', 'Northern Europe'], ['Slovakia', '5,473,197', '5,518,055', '+0.82%', 'Europe', 'Eastern Europe'], ['Liberia', '5,373,294', '5,493,031', '+2.23%', 'Africa', 'Western Africa'], ['Palestine[o]', '5,305,270', '5,409,202', '+1.96%', 'Asia', 'Western Asia'], ['Ireland', '5,110,016', '5,196,630', '+1.69%', 'Europe', 'Northern Europe'], ['New Zealand', '5,131,734', '5,172,836', '+0.80%', 'Oceania', 'Australia and New Zealand'], ['Central African Republic', '5,098,039', '5,152,421', '+1.07%', 'Africa', 'Middle Africa'], ['Costa Rica', '5,081,765', '5,105,525', '+0.47%', 'Americas', 'Central America'], ['Oman', '4,730,226', '5,049,269', '+6.74%', 'Asia', 'Western Asia'], ['Mauritania', '4,875,637', '5,022,441', '+3.01%', 'Africa', 'Western Africa'], ['Kuwait', '4,589,511', '4,838,782', '+5.43%', 'Asia', 'Western Asia'], ['Panama', '4,400,773', '4,458,759', '+1.32%', 'Americas', 'Central America'], ['Croatia', '3,907,027', '3,896,023', '−0.28%', 'Europe', 'Southern Europe'], ['Georgia[p]', '3,794,784', '3,807,492', '+0.33%', 'Asia', 'Western Asia'], ['Eritrea', '3,409,447', '3,470,390', '+1.79%', 'Africa', 'Eastern Africa'], ['Mongolia', '3,386,015', '3,431,932', '+1.36%', 'Asia', 'Eastern Asia'], ['Uruguay', '3,390,913', '3,388,081', '−0.08%', 'Americas', 'South America'], ['Puerto Rico (United States)', '3,240,968', '3,242,023', '+0.03%', 'Americas', 'Caribbean'], ['Bosnia and Herzegovina', '3,204,802', '3,185,073', '−0.62%', 'Europe', 'Southern Europe'], ['Moldova[q]', '3,039,985', '3,067,070', '+0.89%', 'Europe', 'Eastern Europe'], ['Qatar', '2,892,455', '2,979,082', '+2.99%', 'Asia', 'Western Asia'], ['Namibia', '2,889,662', '2,963,095', '+2.54%', 'Africa', 'Southern Africa'], ['Armenia', '2,880,874', '2,943,393', '+2.17%', 'Asia', 'Western Asia'], ['Lithuania', '2,816,919', '2,854,099', '+1.32%', 'Europe', 'Northern Europe'], ['Jamaica', '2,839,144', '2,839,786', '+0.02%', 'Americas', 'Caribbean'], ['Albania', '2,827,608', '2,811,655', '−0.56%', 'Europe', 'Southern Europe'], ['Gambia', '2,636,470', '2,697,845', '+2.33%', 'Africa', 'Western Africa'], ['Gabon', '2,430,747', '2,484,789', '+2.22%', 'Africa', 'Middle Africa'], ['Botswana', '2,439,892', '2,480,244', '+1.65%', 'Africa', 'Southern Africa'], ['Lesotho', '2,286,110', '2,311,472', '+1.11%', 'Africa', 'Southern Africa'], ['Guinea-Bissau', '2,105,529', '2,153,339', '+2.27%', 'Africa', 'Western Africa'], ['Slovenia', '2,115,228', '2,118,396', '+0.15%', 'Europe', 'Southern Europe'], ['Latvia', '1,881,063', '1,882,396', '+0.07%', 'Europe', 'Northern Europe'], ['Equatorial Guinea', '1,803,545', '1,847,549', '+2.44%', 'Africa', 'Middle Africa'], ['North Macedonia', '1,840,233', '1,831,802', '−0.46%', 'Europe', 'Southern Europe'], ['Kosovo[r]', '1,717,946', '1,700,031', '−1.04%', 'Europe', 'Southern Europe'], ['Bahrain', '1,533,459', '1,569,666', '+2.36%', 'Asia', 'Western Asia'], ['Trinidad and Tobago', '1,495,921', '1,502,932', '+0.47%', 'Americas', 'Caribbean'], ['Timor-Leste', '1,369,295', '1,384,286', '+1.09%', 'Asia', 'South-eastern Asia'], ['Estonia', '1,350,091', '1,367,196', '+1.27%', 'Europe', 'Northern Europe'], ['Cyprus[s]', '1,331,370', '1,344,976', '+1.02%', 'Asia', 'Western Asia'], ['Mauritius', '1,276,130', '1,273,588', '−0.20%', 'Africa', 'Eastern Africa'], ['Eswatini', '1,218,917', '1,230,506', '+0.95%', 'Africa', 'Southern Africa'], ['Djibouti', '1,137,096', '1,152,944', '+1.39%', 'Africa', 'Eastern Africa'], ['Fiji', '919,422', '924,145', '+0.51%', 'Oceania', 'Melanesia'], ['Réunion (France)', '871,540', '874,883', '+0.38%', 'Africa', 'Eastern Africa'], ['Comoros', '834,188', '850,387', '+1.94%', 'Africa', 'Eastern Africa'], ['Guyana', '821,637', '826,353', '+0.57%', 'Americas', 'South America'], ['Solomon Islands', '781,066', '800,005', '+2.42%', 'Oceania', 'Melanesia'], ['Bhutan', '780,914', '786,385', '+0.70%', 'Asia', 'Southern Asia'], ['Macao (China)[t]', '704,356', '713,912', '+1.36%', 'Asia', 'Eastern Asia'], ['Luxembourg', '653,313', '665,098', '+1.80%', 'Europe', 'Western Europe'], ['Montenegro', '614,648', '633,552', '+3.08%', 'Europe', 'Southern Europe'], ['Suriname', '623,164', '628,886', '+0.92%', 'Americas', 'South America'], ['Western Sahara (disputed)[u]', '568,739', '579,729', '+1.93%', 'Africa', 'Northern Africa'], ['Malta', '528,192', '532,956', '+0.90%', 'Europe', 'Southern Europe'], ['Maldives', '524,106', '525,994', '+0.36%', 'Asia', 'Southern Asia'], ['Cape Verde', '519,741', '522,331', '+0.50%', 'Africa', 'Western Africa'], ['Brunei', '455,370', '458,949', '+0.79%', 'Asia', 'South-eastern Asia'], ['Belize', '402,733', '411,106', '+2.08%', 'Americas', 'Central America'], ['Bahamas', '397,538', '399,440', '+0.48%', 'Americas', 'Caribbean'], ['Iceland', '380,356', '387,558', '+1.89%', 'Europe', 'Northern Europe'], ['Guadeloupe (France)', '384,697', '376,517', '−2.13%', 'Americas', 'Caribbean'], ['Martinique (France)', '349,459', '346,002', '−0.99%', 'Americas', 'Caribbean'], ['Vanuatu', '313,046', '320,409', '+2.35%', 'Oceania', 'Melanesia'], ['Mayotte (France)', '305,269', '316,015', '+3.52%', 'Africa', 'Eastern Africa'], ['French Guiana (France)', '298,306', '303,402', '+1.71%', 'Americas', 'South America'], ['New Caledonia (France)', '287,123', '289,870', '+0.96%', 'Oceania', 'Melanesia'], ['Barbados', '288,318', '282,336', '−2.07%', 'Americas', 'Caribbean'], ['French Polynesia (France)', '280,378', '281,118', '+0.26%', 'Oceania', 'Polynesia'], ['São Tomé and Príncipe', '226,305', '230,871', '+2.02%', 'Africa', 'Middle Africa'], ['Samoa', '215,261', '216,663', '+0.65%', 'Oceania', 'Polynesia'], ['Curaçao (Netherlands)', '185,345', '185,427', '+0.04%', 'Americas', 'Caribbean'], ['Saint Lucia', '178,781', '179,285', '+0.28%', 'Americas', 'Caribbean'], ['Guam (United States)', '165,180', '166,506', '+0.80%', 'Oceania', 'Micronesia'], ['Kiribati', '130,469', '132,530', '+1.58%', 'Oceania', 'Micronesia'], ['Seychelles', '125,522', '127,951', '+1.94%', 'Africa', 'Eastern Africa'], ['Grenada', '116,913', '117,081', '+0.14%', 'Americas', 'Caribbean'], ['Micronesia', '112,114', '112,630', '+0.46%', 'Oceania', 'Micronesia'], ['Tonga', '105,042', '104,597', '−0.42%', 'Oceania', 'Polynesia'], ['Aruba (Netherlands)', '107,782', '107,939', '+0.15%', 'Americas', 'Caribbean'], ['Jersey (United Kingdom)', '103,490', '103,674', '+0.18%', 'Europe', 'Northern Europe'], ['Saint Vincent and the Grenadines', '102,046', '101,323', '−0.71%', 'Americas', 'Caribbean'], ['Antigua and Barbuda', '92,840', '93,316', '+0.51%', 'Americas', 'Caribbean'], ['U.S. Virgin Islands (United States)', '86,507', '85,701', '−0.93%', 'Americas', 'Caribbean'], ['Isle of Man (United Kingdom)', '84,132', '84,165', '+0.04%', 'Europe', 'Northern Europe'], ['Andorra', '79,705', '80,856', '+1.44%', 'Europe', 'Southern Europe'], ['Cayman Islands (United Kingdom)', '71,591', '73,038', '+2.02%', 'Americas', 'Caribbean'], ['Dominica', '66,826', '66,510', '−0.47%', 'Americas', 'Caribbean'], ['Bermuda (United Kingdom)', '64,749', '64,698', '−0.08%', 'Americas', 'Northern America'], ['Guernsey (United Kingdom)', '63,725', '64,017', '+0.46%', 'Europe', 'Northern Europe'], ['Greenland (Denmark)', '54,990', '55,922', '+1.69%', 'Americas', 'Northern America'], ['Faroe Islands (Denmark)', '54,011', '54,714', '+1.30%', 'Europe', 'Northern Europe'], ['American Samoa (United States)', '48,342', '47,521', '−1.70%', 'Oceania', 'Polynesia'], ['Saint Kitts and Nevis', '46,709', '46,758', '+0.10%', 'Americas', 'Caribbean'], ['Turks and Caicos Islands (United Kingdom)', '45,847', '46,198', '+0.77%', 'Americas', 'Caribbean'], ['Northern Mariana Islands (United States)', '46,078', '45,143', '−2.03%', 'Oceania', 'Micronesia'], ['Sint Maarten (Netherlands)', '42,139', '42,749', '+1.45%', 'Americas', 'Caribbean'], ['Liechtenstein', '39,317', '39,598', '+0.71%', 'Europe', 'Western Europe'], ['British Virgin Islands (United Kingdom)', '38,319', '38,985', '+1.74%', 'Americas', 'Caribbean'], ['Monaco', '38,931', '38,956', '+0.06%', 'Europe', 'Western Europe'], ['Gibraltar (United Kingdom)', '37,609', '38,471', '+2.29%', 'Europe', 'Southern Europe'], ['Marshall Islands', '40,077', '38,827', '−3.12%', 'Oceania', 'Micronesia'], ['San Marino', '34,090', '33,733', '−1.05%', 'Europe', 'Southern Europe'], ['Caribbean Netherlands (Netherlands)[v]', '28,627', '29,898', '+4.44%', 'Americas', 'Caribbean'], ['Saint Martin (France)', '28,870', '27,515', '−4.69%', 'Americas', 'Caribbean'], ['Palau', '17,759', '17,727', '−0.18%', 'Oceania', 'Micronesia'], ['Anguilla (United Kingdom)', '14,180', '14,410', '+1.62%', 'Americas', 'Caribbean'], ['Cook Islands (New Zealand)', '14,723', '14,222', '−3.40%', 'Oceania', 'Polynesia'], ['Nauru', '11,801', '11,875', '+0.63%', 'Oceania', 'Micronesia'], ['Wallis and Futuna (France)', '11,478', '11,370', '−0.94%', 'Oceania', 'Polynesia'], ['Saint Barthélemy (France)', '10,920', '11,085', '+1.51%', 'Americas', 'Caribbean'], ['Tuvalu', '9,992', '9,816', '−1.76%', 'Oceania', 'Polynesia'], ['Saint Pierre and Miquelon (France)', '5,732', '5,681', '−0.89%', 'Americas', 'Northern America'], ['Saint Helena (United Kingdom)[w]', '5,343', '5,289', '−1.01%', 'Africa', 'Western Africa'], ['Montserrat (United Kingdom)', '4,453', '4,420', '−0.74%', 'Americas', 'Caribbean'], ['Falkland Islands (United Kingdom)', '3,490', '3,477', '−0.37%', 'Americas', 'South America'], ['Tokelau (New Zealand)', '2,290', '2,397', '+4.67%', 'Oceania', 'Polynesia'], ['Niue (New Zealand)', '1,821', '1,817', '−0.22%', 'Oceania', 'Polynesia'], ['Vatican City[x]', '505', '496', '−1.78%', 'Europe', 'Southern Europe']]

In [96]:
df = pd.DataFrame(rows, columns=headers)
df

,Country or territory,Population(1 July 2022),Population(1 July 2023),Change(%),UN continentalregion[1],UN statisticalsubregion[1]
0,World,"8,021,407,192","8,091,734,930",+0.88%,–,–
1,India,"1,425,423,212","1,438,069,596",+0.89%,Asia,Southern Asia
2,China[a],"1,425,179,569","1,422,584,933",−0.18%,Asia,Eastern Asia
3,United States,"341,534,046","343,477,335",+0.57%,Americas,Northern America
4,Indonesia,"278,830,529","281,190,067",+0.85%,Asia,South-eastern Asia
...,...,...,...,...,...,...
233,Montserrat (United Kingdom),"4,453","4,420",−0.74%,Americas,Caribbean
234,Falkland Islands (United Kingdom),"3,490","3,477",−0.37%,Americas,South America
235,Tokelau (New Zealand),"2,290","2,397",+4.67%,Oceania,Polynesia
236,Niue (New Zealand),"1,821","1,817",−0.22%,Oceania,Polynesia
237,Vatican City[x],505,496,−1.78%,Europe,Southern Europe

In [97]:
df.to_csv('countries_population.csv', index=False)
print("Data saved to 'countries_population.csv'")

Data saved to 'countries_population.csv'

# Second Data

In [98]:
page2 = requests.get("https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_area")
src2 = page2.content
soup2 = BeautifulSoup(src2, 'html.parser')
print(soup2)

<!DOCTYPE html>

<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>List of countries and dependencies by area - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy",
"wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"d60f5cf6-dc68-4e13-aef3-e9023fd0c7c7","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_countries_and_dependencies_by_area","wgTitle":"List of countries and dependencies by area","wgCurRevisionId":1277584502,"wgRevisionId":1277584502,"wgArticleId":3989609,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["CS1 French-language sources (fr)","CS1: long volume value","CS1 Japanese-language sources (ja)","Webarchive template wayback links","Articles with Italian-language sources (it)","Articles with short description","Short description is different from Wikidata","Wikipedia pages semi-protected against vandalism","Use dmy dates from January 2022","Water by country","Lists by area","Lists of countries by geography",
"Geography-related lists","International rankings"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_countries_and_dependencies_by_area","wgRelevantArticleId":3989609,"wgIsProbablyEditable":false,"wgRelevantPageIsProbablyEditable":false,"wgRestrictionEdit":["autoconfirmed"],"wgRestrictionMove":["autoconfirmed"],"wgNoticeProject":"wikipedia","wgCiteReferencePreviewsActive":false,"wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":80000,"wgEditSubmitButtonLabelPublish":true,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,
"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q260023","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGETopicsMatchModeEnabled":false,"wgGEStructuredTaskRejectionReasonTextInputEnabled":false,"wgGELevelingUpEnabledForUser":false};RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","ext.wikimediamessages.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wikimediaBadges":"ready"};RLPAGEMODULES=["ext.cite.ux-enhancements","mediawiki.page.media",
"site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.visualEditor.targetLoader","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","ext.checkUser.clientHints","ext.growthExperiments.SuggestedEditSession"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cext.wikimediamessages.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta content="" name="ResourceLoaderDynamicStyles"/>
<link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
<meta content="MediaWiki 1.44.0-wmf.17" name="generator"/>
<meta content="origin" name="referrer"/>
<meta content="origin-when-cross-origin" name="referrer"/>
<meta content="max-image-preview:standard" name="robots"/>
<meta content="telephone=no" name="format-detection"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Fuller_projection_with_largest_countries.svg/1200px-Fuller_projection_with_largest_countries.svg.png" property="og:image"/>
<meta content="1200" property="og:image:width"/>
<meta content="799" property="og:image:height"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Fuller_projection_with_largest_countries.svg/800px-Fuller_projection_with_largest_countries.svg.png" property="og:image"/>
<meta content="800" property="og:image:width"/>
<meta content="533" property="og:image:height"/>
<meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Fuller_projection_with_largest_countries.svg/640px-Fuller_projection_with_largest_countries.svg.png" property="og:image"/>
<meta content="640" property="og:image:width"/>
<meta content="426" property="og:image:height"/>
<meta content="width=1120" name="viewport"/>
<meta content="List of countries and dependencies by area - Wikipedia" property="og:title"/>
<meta content="website" property="og:type"/>
<link href="//upload.wikimedia.org" rel="preconnect"/>
<link href="//en.m.wikipedia.org/wiki/List_of_countries_and_dependencies_by_area" media="only screen and (max-width: 640px)" rel="alternate"/>
<link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
<link href="/static/favicon/wikipedia.ico" rel="icon"/>
<link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
<link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
<link href="https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_area" rel="canonical"/>
<link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
<link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
<link href="//meta.wikimedia.org" rel="dns-prefetch">
<link href="login.wikimedia.org" rel="dns-prefetch"/>
</link></head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject page-List_of_countries_and_dependencies_by_area rootpage-List_of_countries_and_dependencies_by_area skin-vector-2022 action-view"><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
<header class="vector-header mw-header">
<div class="vector-header-start">
<nav aria-label="Site" class="vector-main-menu-landmark">
<div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
<input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label"><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>
<span class="vector-dropdown-label-text">Main menu</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
<div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
<div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
<div class="vector-pinnable-header-label">Main menu</div>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>
<div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
<div class="vector-menu-heading">
		Navigation
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-mainpage-description"><a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a></li><li class="mw-list-item" id="n-contents"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li class="mw-list-item" id="n-currentevents"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li class="mw-list-item" id="n-randompage"><a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a></li><li class="mw-list-item" id="n-aboutsite"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li class="mw-list-item" id="n-contactpage"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
<div class="vector-menu-heading">
		Contribute
	</div>
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="mw-list-item" id="n-help"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li class="mw-list-item" id="n-introduction"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li class="mw-list-item" id="n-portal"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li class="mw-list-item" id="n-recentchanges"><a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a></li><li class="mw-list-item" id="n-upload"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li class="mw-list-item" id="n-specialpages"><a href="/wiki/Special:SpecialPages"><span>Special pages</span></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</nav>
<a class="mw-logo" href="/wiki/Main_Page">
<img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/wikipedia.png" width="50"/>
<span class="mw-logo-container skin-invert">
<img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;"/>
<img alt="The Free Encyclopedia" class="mw-logo-tagline" height="13" src="/static/images/mobile/copyright/wikipedia-tagline-en.svg" style="width: 7.3125em; height: 0.8125em;" width="117"/>
</span>
</a>
</div>
<div class="vector-header-end">
<div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
<a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
<span>Search</span>
</a>
<div class="vector-typeahead-search-container">
<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
<form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
<div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
<div class="cdx-text-input cdx-text-input--has-start-icon">
<input accesskey="f" aria-label="Search Wikipedia" autocapitalize="sentences" class="cdx-text-input__input" id="searchInput" name="search" placeholder="Search Wikipedia" title="Search Wikipedia [f]" type="search"/>
<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
</div>
<input name="title" type="hidden" value="Special:Search"/>
</div>
<button class="cdx-button cdx-search-input__end-button">Search</button>
</form>
</div>
</div>
</div>
<nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
<div class="vector-user-links-main">
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<nav aria-label="Appearance" class="vector-appearance-landmark">
<div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
<input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label"><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>
<span class="vector-dropdown-label-text">Appearance</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
</div>
</div>
</div>
</nav>
<div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
</ul>
</div>
</div>
<div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-sitesupport-2"><a class="" data-mw="interface" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2"><a class="" data-mw="interface" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+countries+and+dependencies+by+area" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>
</li>
<li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2"><a accesskey="o" class="" data-mw="interface" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+countries+and+dependencies+by+area" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>
</li>
</ul>
</div>
</div>
</div>
<div class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out" id="vector-user-links-dropdown" title="Log in and more options">
<input aria-haspopup="true" aria-label="Personal tools" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-user-links-dropdown" id="vector-user-links-dropdown-checkbox" role="button" type="checkbox"/>
<label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-user-links-dropdown-checkbox" id="vector-user-links-dropdown-label"><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>
<span class="vector-dropdown-label-text">Personal tools</span>
</label>
<div class="vector-dropdown-content">
<div class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item" id="p-personal" title="User menu">
<div class="vector-menu-content">
<ul class="vector-menu-content-list">
<li class="user-links-collapsible-item mw-list-item" id="pt-sitesupport"><a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-createaccount"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+countries+and+dependencies+by+area" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a></li><li class="user-links-collapsible-item mw-list-item" id="pt-login"><a accesskey="o" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+countries+and+dependencies+by+area" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a></li>
</ul>
</div>
</div>
<div class="vector-menu mw-portlet mw-portlet-user-menu-anon-editor" id="p-user-menu-anon-editor">
<div class="vector-menu-heading">

In [99]:
table2 = soup2.find('table', {'class': 'wikitable'})
print(table2)

<table class="wikitable sortable sticky-header col2left" style="text-align:right">
<tbody><tr>
<th></th>
<th style="width:18em">Country / dependency
</th>
<th data-sort-type="number" style="width:9.7em">Total<br/>in km<sup>2</sup> (mi<sup>2</sup>)
</th>
<th data-sort-type="number" style="width:9.7em">Land<br/>in km<sup>2</sup> (mi<sup>2</sup>)
</th>
<th data-sort-type="number" style="width:7.5em">Water<br/>in km<sup>2</sup> (mi<sup>2</sup>)
</th>
<th data-sort-type="number">%<br/>water</th>
<th class="unsortable">
</th></tr>
<tr>
<td><span data-sort-value="5000000000000000000♠" style="display:none"></span> –</td>
<td><b><span class="flagicon" style="padding-left:25px;"> </span><a href="/wiki/Earth" title="Earth">Earth</a></b></td>
<td>510,072,000 (196,940,000)</td>
<td>148,940,000 (57,506,000)</td>
<td>361,132,000 (139,434,000)</td>
<td>70.8</td>
<td>
</td></tr>
<tr>
<td><span data-sort-value="7000100000000000000♠">1</span></td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/23px-Flag_of_Russia.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/35px-Flag_of_Russia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/45px-Flag_of_Russia.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Russia" title="Russia">Russia</a></td>
<td>17,098,246 (6,601,667)</td>
<td>16,376,870 (6,323,142)</td>
<td>721,380 (278,530)</td>
<td>4.2</td>
<td><sup class="reference" id="cite_ref-6"><a href="#cite_note-6"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="1vend" style="display:none;"></span> –</td>
<td><i><span class="flagicon" style="padding-left:25px;"> </span><a href="/wiki/Antarctica" title="Antarctica">Antarctica</a></i></td>
<td>14,200,000 (5,480,000)</td>
<td>14,200,000 (5,480,000)</td>
<td>0</td>
<td>0</td>
<td><sup class="reference" id="cite_ref-7"><a href="#cite_note-7"><span class="cite-bracket">[</span>c<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="7000200000000000000♠">2</span></td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/23px-Flag_of_Canada_%28Pantone%29.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/35px-Flag_of_Canada_%28Pantone%29.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/46px-Flag_of_Canada_%28Pantone%29.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Canada" title="Canada">Canada</a></td>
<td>9,984,670 (3,855,100)</td>
<td>9,093,507 (3,511,021)</td>
<td>891,163 (344,080)</td>
<td>8.9</td>
<td><sup class="reference" id="cite_ref-10"><a href="#cite_note-10"><span class="cite-bracket">[</span>d<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td rowspan="2"><span class="nowrap"> <span data-sort-value="7000300000000000000♠">3</span>/4</span><br/><sup class="reference" id="cite_ref-12"><a href="#cite_note-12"><span class="cite-bracket">[</span>e<span class="cite-bracket">]</span></a></sup>
</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/China" title="China">China</a></td>
<td>9,596,960 (3,705,410)</td>
<td>9,326,410 (3,600,950)</td>
<td>270,550 (104,460)</td>
<td>2.8</td>
<td><sup class="reference" id="cite_ref-13"><a href="#cite_note-13"><span class="cite-bracket">[</span>f<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td style="text-align:left"><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/United_States" title="United States">United States</a></td>
<td style="text-align:right">9,525,067 (3,677,647)</td>
<td>9,147,593 (3,531,904)</td>
<td>377,424 (145,724)</td>
<td>4.0</td>
<td><sup class="reference" id="cite_ref-17"><a href="#cite_note-17"><span class="cite-bracket">[</span>g<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="7000500000000000000♠">5</span></td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="700" data-file-width="1000" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/22px-Flag_of_Brazil.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/33px-Flag_of_Brazil.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/43px-Flag_of_Brazil.svg.png 2x" width="22"/></span></span> </span><a href="/wiki/Brazil" title="Brazil">Brazil</a></td>
<td>8,510,346 (3,285,862)</td>
<td>8,460,415 (3,266,583)</td>
<td>55,352 (21,372)</td>
<td>0.6</td>
<td><sup class="reference" id="cite_ref-18"><a href="#cite_note-18"><span class="cite-bracket">[</span>h<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="7000600000000000000♠">6</span></td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="256" data-file-width="512" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/23px-Flag_of_Australia_%28converted%29.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/35px-Flag_of_Australia_%28converted%29.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/46px-Flag_of_Australia_%28converted%29.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Australia" title="Australia">Australia</a></td>
<td>7,741,220 (2,988,900)</td>
<td>7,682,300 (2,966,200)</td>
<td>58,920 (22,750)</td>
<td>0.8</td>
<td><sup class="reference" id="cite_ref-21"><a href="#cite_note-21"><span class="cite-bracket">[</span>i<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="7000700000000000000♠">7</span></td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/35px-Flag_of_India.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/45px-Flag_of_India.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/India" title="India">India</a></td>
<td>3,287,263 (1,269,219)</td>
<td>2,973,190 (1,147,960)</td>
<td>314,070 (121,260)</td>
<td>9.6</td>
<td><sup class="reference" id="cite_ref-22"><a href="#cite_note-22"><span class="cite-bracket">[</span>j<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="7000800000000000000♠">8</span></td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="500" data-file-width="800" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/23px-Flag_of_Argentina.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/35px-Flag_of_Argentina.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/46px-Flag_of_Argentina.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Argentina" title="Argentina">Argentina</a></td>
<td>2,780,400 (1,073,500)</td>
<td>2,736,690 (1,056,640)</td>
<td>43,710 (16,880)</td>
<td>1.6</td>
<td><sup class="reference" id="cite_ref-23"><a href="#cite_note-23"><span class="cite-bracket">[</span>k<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="7000900000000000000♠">9</span></td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="500" data-file-width="1000" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/23px-Flag_of_Kazakhstan.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/35px-Flag_of_Kazakhstan.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/46px-Flag_of_Kazakhstan.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Kazakhstan" title="Kazakhstan">Kazakhstan</a></td>
<td>2,724,910 (1,052,090)</td>
<td>2,699,700 (1,042,400)</td>
<td>25,202 (9,731)</td>
<td>0.9</td>
<td><sup class="reference" id="cite_ref-24"><a href="#cite_note-24"><span class="cite-bracket">[</span>l<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="7001100000000000000♠">10</span></td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/23px-Flag_of_Algeria.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/35px-Flag_of_Algeria.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/45px-Flag_of_Algeria.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Algeria" title="Algeria">Algeria</a></td>
<td>2,381,741 (919,595)</td>
<td>2,381,741 (919,595)</td>
<td>0</td>
<td>0</td>
<td><sup class="reference" id="cite_ref-26"><a href="#cite_note-26"><span class="cite-bracket">[</span>m<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="7001110000000000000♠">11</span></td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="800" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/20px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/31px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/40px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png 2x" width="20"/></span></span> </span><a href="/wiki/Democratic_Republic_of_the_Congo" title="Democratic Republic of the Congo">Democratic Republic of the Congo</a></td>
<td>2,344,858 (905,354)</td>
<td>2,267,048 (875,312)</td>
<td>77,810 (30,040)</td>
<td>3.3</td>
<td><sup class="reference" id="cite_ref-27"><a href="#cite_note-27"><span class="cite-bracket">[</span>n<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="end" style="display:none;"></span> –</td>
<td><i><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><a href="/wiki/Denmark" title="Denmark"><img alt="Denmark" class="mw-file-element" data-file-height="387" data-file-width="512" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/20px-Flag_of_Denmark.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/31px-Flag_of_Denmark.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/40px-Flag_of_Denmark.svg.png 2x" width="20"/></a></span></span> <a href="/wiki/Danish_Realm" title="Danish Realm">Kingdom of Denmark</a></i></td>
<td>2,210,573 (853,507)</td>
<td>2,209,913 (853,252)</td>
<td>660 (260)</td>
<td>0.0</td>
<td><sup class="reference" id="cite_ref-28"><a href="#cite_note-28"><span class="cite-bracket">[</span>o<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="end" style="display:none;"></span> –</td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/23px-Flag_of_Greenland.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/35px-Flag_of_Greenland.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/45px-Flag_of_Greenland.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Greenland" title="Greenland">Greenland</a> (<a href="/wiki/Denmark" title="Denmark">Denmark</a>)</td>
<td>2,166,086 (836,330)</td>
<td>2,166,086 (836,330)</td>
<td>0</td>
<td>0</td>
<td><sup class="reference" id="cite_ref-29"><a href="#cite_note-29"><span class="cite-bracket">[</span>p<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="7001120000000000000♠">12</span></td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/23px-Flag_of_Saudi_Arabia.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/35px-Flag_of_Saudi_Arabia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/45px-Flag_of_Saudi_Arabia.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Saudi_Arabia" title="Saudi Arabia">Saudi Arabia</a></td>
<td>2,149,690 (830,000)</td>
<td>2,149,690 (830,000)</td>
<td>0</td>
<td>0</td>
<td><sup class="reference" id="cite_ref-ciadata_30-0"><a href="#cite_note-ciadata-30"><span class="cite-bracket">[</span>q<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="7001130000000000000♠">13</span></td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="560" data-file-width="980" decoding="async" height="13" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/23px-Flag_of_Mexico.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/35px-Flag_of_Mexico.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/46px-Flag_of_Mexico.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Mexico" title="Mexico">Mexico</a></td>
<td>1,964,375 (758,449)</td>
<td>1,943,950 (750,563)</td>
<td>20,425 (7,886)</td>
<td>1.0</td>
<td>
</td></tr>
<tr>
<td><span data-sort-value="7001140000000000000♠">14</span></td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/23px-Flag_of_Indonesia.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/35px-Flag_of_Indonesia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/45px-Flag_of_Indonesia.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Indonesia" title="Indonesia">Indonesia</a></td>
<td>1,904,569 (735,358)</td>
<td>1,811,569 (699,450)</td>
<td>93,000 (36,000)</td>
<td>4.9</td>
<td><sup class="reference" id="cite_ref-31"><a href="#cite_note-31"><span class="cite-bracket">[</span>r<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="7001150000000000000♠">15</span></td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="600" data-file-width="1200" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/23px-Flag_of_Sudan.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/35px-Flag_of_Sudan.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/46px-Flag_of_Sudan.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Sudan" title="Sudan">Sudan</a></td>
<td>1,861,484 (718,723)</td>
<td>1,731,671 (668,602)</td>
<td>129,813 (50,121)</td>
<td>7.0</td>
<td><sup class="reference" id="cite_ref-ciadata_30-1"><a href="#cite_note-ciadata-30"><span class="cite-bracket">[</span>q<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="7001160000000000000♠">16</span></td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="480" data-file-width="960" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/23px-Flag_of_Libya.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/35px-Flag_of_Libya.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/46px-Flag_of_Libya.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Libya" title="Libya">Libya</a></td>
<td>1,759,540 (679,362)</td>
<td>1,759,540 (679,362)</td>
<td>0</td>
<td>0</td>
<td><sup class="reference" id="cite_ref-ciadata_30-2"><a href="#cite_note-ciadata-30"><span class="cite-bracket">[</span>q<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="7001170000000000000♠">17</span></td>
<td><span class="flagicon"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="360" data-file-width="630" decoding="async" height="13" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/35px-Flag_of_Iran.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/46px-Flag_of_Iran.svg.png 2x" width="23"/></span></span> </span><a href="/wiki/Iran" title="Iran">Iran</a></td>
<td>1,648,195 (636,371)</td>
<td>1,531,595 (591,352)</td>
<td>116,600 (45,020)</td>
<td>7.1</td>
<td><sup class="reference" id="cite_ref-32"><a href="#cite_note-32"><span class="cite-bracket">[</span>s<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><span data-sort-value="7001180000000000000♠">18</span></td>

In [101]:
table_of_th2 = table2.find_all('th')
print(table_of_th2)

[<th></th>, <th style="width:18em">Country / dependency
</th>, <th data-sort-type="number" style="width:9.7em">Total<br/>in km<sup>2</sup> (mi<sup>2</sup>)
</th>, <th data-sort-type="number" style="width:9.7em">Land<br/>in km<sup>2</sup> (mi<sup>2</sup>)
</th>, <th data-sort-type="number" style="width:7.5em">Water<br/>in km<sup>2</sup> (mi<sup>2</sup>)
</th>, <th data-sort-type="number">%<br/>water</th>, <th class="unsortable">
</th>]

In [102]:
headers2 = []
for th2 in table_of_th2 :
    headers2.append(th2.text.strip())
print(headers2)

['', 'Country / dependency', 'Totalin km2 (mi2)', 'Landin km2 (mi2)', 'Waterin km2 (mi2)', '%water', '']

In [103]:
rows2 = []
for row2 in table2.find_all('tr')[1:]:  
    columns2 = row2.find_all('td')
    if len(columns2) > 1:  # Ensure the row has data
        row_data2 = [col2.text.strip() for col2 in columns2]
        rows2.append(row_data2)
print(rows2)

[['–', 'Earth', '510,072,000 (196,940,000)', '148,940,000 (57,506,000)', '361,132,000 (139,434,000)', '70.8', ''], ['1', 'Russia', '17,098,246 (6,601,667)', '16,376,870 (6,323,142)', '721,380 (278,530)', '4.2', '[b]'], ['–', 'Antarctica', '14,200,000 (5,480,000)', '14,200,000 (5,480,000)', '0', '0', '[c]'], ['2', 'Canada', '9,984,670 (3,855,100)', '9,093,507 (3,511,021)', '891,163 (344,080)', '8.9', '[d]'], ['3/4[e]', 'China', '9,596,960 (3,705,410)', '9,326,410 (3,600,950)', '270,550 (104,460)', '2.8', '[f]'], ['United States', '9,525,067 (3,677,647)', '9,147,593 (3,531,904)', '377,424 (145,724)', '4.0', '[g]'], ['5', 'Brazil', '8,510,346 (3,285,862)', '8,460,415 (3,266,583)', '55,352 (21,372)', '0.6', '[h]'], ['6', 'Australia', '7,741,220 (2,988,900)', '7,682,300 (2,966,200)', '58,920 (22,750)', '0.8', '[i]'], ['7', 'India', '3,287,263 (1,269,219)', '2,973,190 (1,147,960)', '314,070 (121,260)', '9.6', '[j]'], ['8', 'Argentina', '2,780,400 (1,073,500)', '2,736,690 (1,056,640)', '43,710 (16,880)', '1.6', '[k]'], ['9', 'Kazakhstan', '2,724,910 (1,052,090)', '2,699,700 (1,042,400)', '25,202 (9,731)', '0.9', '[l]'], ['10', 'Algeria', '2,381,741 (919,595)', '2,381,741 (919,595)', '0', '0', '[m]'], ['11', 'Democratic Republic of the Congo', '2,344,858 (905,354)', '2,267,048 (875,312)', '77,810 (30,040)', '3.3', '[n]'], ['–', 'Kingdom of Denmark', '2,210,573 (853,507)', '2,209,913 (853,252)', '660 (260)', '0.0', '[o]'], ['–', 'Greenland (Denmark)', '2,166,086 (836,330)', '2,166,086 (836,330)', '0', '0', '[p]'], ['12', 'Saudi Arabia', '2,149,690 (830,000)', '2,149,690 (830,000)', '0', '0', '[q]'], ['13', 'Mexico', '1,964,375 (758,449)', '1,943,950 (750,563)', '20,425 (7,886)', '1.0', ''], ['14', 'Indonesia', '1,904,569 (735,358)', '1,811,569 (699,450)', '93,000 (36,000)', '4.9', '[r]'], ['15', 'Sudan', '1,861,484 (718,723)', '1,731,671 (668,602)', '129,813 (50,121)', '7.0', '[q]'], ['16', 'Libya', '1,759,540 (679,362)', '1,759,540 (679,362)', '0', '0', '[q]'], ['17', 'Iran', '1,648,195 (636,371)', '1,531,595 (591,352)', '116,600 (45,020)', '7.1', '[s]'], ['18', 'Mongolia', '1,564,116 (603,908)', '1,557,507 (601,357)', '6,609 (2,552)', '0.4', ''], ['19', 'Peru', '1,285,216 (496,224)', '1,279,996 (494,209)', '5,220 (2,020)', '0.4', ''], ['20', 'Chad', '1,284,000 (495,800)', '1,259,200 (486,180)', '24,800 (9,580)', '1.9', '[t]'], ['21', 'Niger', '1,267,000 (489,200)', '1,266,700 (489,080)', '300 (100)', '0', ''], ['22', 'Angola', '1,246,700 (481,350)', '1,246,700 (481,350)', '0', '0', ''], ['23', 'Mali', '1,240,192 (478,841)', '1,220,190 (471,118)', '20,000 (8,000)', '1.6', ''], ['24', 'South Africa', '1,219,090 (470,693)', '1,214,470 (468,909)', '4,620 (1,780)', '0.4', '[q]'], ['25', 'Colombia', '1,138,910 (439,735)', '1,038,700 (401,040)', '100,210 (38,691)', '8.8', '[q]'], ['26', 'Ethiopia', '1,104,300 (426,370)', '1,096,570 (423,388)', '7,730 (2,990)', '0.7', '[u]'], ['27', 'Bolivia', '1,098,581 (424,164)', '1,083,300 (418,260)', '15,280 (5,900)', '1.4', ''], ['28', 'Mauritania', '1,030,700 (397,960)', '1,030,700 (397,960)', '0 (0)', '0', ''], ['29', 'Egypt', '1,001,450 (386,662)', '995,450 (384,350)', '6,000 (2,000)', '0.6', '[v]'], ['30', 'Tanzania', '947,303 (365,756)', '885,800 (342,000)', '61,500 (23,700)', '6.5', ''], ['31', 'Nigeria', '923,768 (356,669)', '910,770 (351,650)', '13,000 (5,000)', '1.4', ''], ['32', 'Venezuela', '912,050 (352,140)', '882,050 (340,560)', '30,000 (10,000)', '3.3', '[w]'], ['33', 'Pakistan', '882,363 (340,682)', '857,143 (330,945)', '25,220 (9,737)', '2.9', '[x]'], ['34', 'Namibia', '824,292 (318,261)', '823,290 (317,870)', '1,002 (387)', '0.1', '[q]'], ['35', 'Mozambique', '799,380 (308,640)', '786,380 (303,620)', '13,000 (5,000)', '1.6', ''], ['36', 'Turkey', '783,562 (302,535)', '769,632 (297,156)', '13,930 (5,378)', '1.8', '[y]'], ['37', 'Chile', '756,102 (291,932)', '743,812 (287,187)', '12,290 (4,745)', '1.6', '[z]'], ['38', 'Zambia', '752,612 (290,585)', '743,390 (287,020)', '9,220 (3,560)', '1.2', ''], ['39', 'Myanmar', '676,578 (261,228)', '653,508 (252,321)', '23,070 (8,907)', '3.4', ''], ['40', 'Afghanistan', '652,864 (252,072)', '652,230 (251,830)', '630 (240)', '0.1', ''], ['41', 'South Sudan', '644,329 (248,777)', '', '', '', '[aa]'], ['42', 'France', '643,801 (248,573)', '640,427 (247,270)', '3,374 (1,303)', '0.5', '[ab]'], ['43', 'Somalia', '637,657 (246,201)', '627,340 (242,220)', '10,320 (3,985)', '1.6', '[ac]'], ['44', 'Central African Republic', '622,984 (240,535)', '622,984 (240,535)', '0', '0', ''], ['45', 'Ukraine', '603,550 (233,030)', '579,330 (223,680)', '24,220 (9,351)', '4.0', '[ad]'], ['46', 'Madagascar', '587,041 (226,658)', '581,540 (224,530)', '5,501 (2,124)', '0.9', ''], ['47', 'Botswana', '582,000 (225,000)', '566,730 (218,820)', '15,000 (5,800)', '2.6', '[q]'], ['48', 'Kenya', '580,367 (224,081)', '569,140 (219,750)', '11,227 (4,335)', '1.9', '[ae]'], ['–', 'France (metropolitan)', '551,500 (212,900)', '549,970 (212,350)', '1,530 (591)', '0.3', '[af]'], ['49', 'Thailand', '513,120 (198,120)', '510,890 (197,260)', '2,230 (861)', '0.4', ''], ['50', 'Spain', '505,370 (195,120)', '498,980 (192,660)', '6,390 (2,470)', '1.3', ''], ['51', 'Turkmenistan', '488,100 (188,500)', '469,930 (181,440)', '18,170 (7,015)', '3.7', ''], ['52', 'Cameroon', '475,650 (183,650)', '472,710 (182,510)', '2,730 (1,050)', '0.6', '[q]'], ['53', 'Papua New Guinea', '462,840 (178,700)', '452,860 (174,850)', '9,980 (3,850)', '2.2', ''], ['54', 'Yemen', '455,503 (175,871)', '455,503 (175,871)', '0', '0', '[ag]'], ['55', 'Sweden', '450,295 (173,860)', '407,284 (157,253)', '40,142 (15,499)', '9.0', '[ah]'], ['56', 'Uzbekistan', '447,400 (172,700)', '425,400 (164,200)', '22,000 (8,500)', '4.9', ''], ['57', 'Morocco', '446,550 (172,410)', '446,300 (172,300)', '250 (97)', '0.1', '[ai]'], ['58', 'Iraq', '438,317 (169,235)', '437,367 (168,868)', '950 (370)', '0.2', '[aj]'], ['59', 'Paraguay', '406,752 (157,048)', '397,300 (153,400)', '9,452 (3,649)', '2.3', ''], ['60', 'Zimbabwe', '390,757 (150,872)', '386,850 (149,360)', '3,910 (1,510)', '1.0', ''], ['61', 'Norway', '386,224 (149,122)', '366,704 (141,585)', '19,520 (7,537)', '5.1', '[ak]'], ['62', 'Japan', '377,915 (145,914)', '364,485 (140,728)', '13,430 (5,185)', '3.6', '[al]'], ['63', 'Germany', '357,581 (138,063)', '349,390 (134,900)', '7,860 (3,040)', '2.2', '[am]'], ['64', 'Republic of the Congo', '342,000 (132,000)', '341,500 (131,900)', '500 (200)', '0.1', ''], ['65', 'Finland', '338,145 (130,558)', '303,815 (117,304)', '34,330 (13,260)', '10.2', '[an]'], ['66', 'Vietnam', '331,340 (127,930)', '313,429 (121,016)', '17,801 (6,873)', '5.4', ''], ['67', 'Malaysia', '330,621 (127,653)', '329,432 (127,194)', '1,190 (459)', '0.4', ''], ['–', 'Norway (mainland)', '323,802 (125,021)', '304,282 (117,484)', '19,520 (7,537)', '6.0', '[ao]'], ['68', 'Ivory Coast', '322,462 (124,503)', '318,000 (123,000)', '4,460 (1,720)', '1.4', ''], ['69', 'Poland', '312,685 (120,728)', '304,255 (117,473)', '8,430 (3,260)', '3.7', ''], ['70', 'Oman', '309,500 (119,500)', '309,500 (119,500)', '0', '0', '[q]'], ['71', 'Italy', '302,068 (116,629)', '295,717 (114,177)', '6,350 (2,450)', '2.1', ''], ['72', 'Philippines', '300,000 (100,000)', '298,170 (115,120)', '1,830 (707)', '0.6', '[ap]'], ['73', 'Ecuador', '283,561 (109,483)', '276,841 (106,889)', '6,720 (2,600)', '2.4', '[aq]'], ['74', 'Burkina Faso', '274,200 (105,900)', '273,800 (105,700)', '400 (200)', '0.2', '[q]'], ['75', 'New Zealand', '268,838 (103,799)', '264,537 (102,138)', '4,301 (1,661)', '1.6', '[ar]'], ['76', 'Gabon', '267,668 (103,347)', '257,670 (99,487)', '10,000 (4,000)', '3.7', ''], ['–', 'Western Sahara', '266,000 (103,000)', '266,000 (103,000)', '0', '0', '[as]'], ['77', 'Guinea', '245,857 (94,926)', '245,717 (94,872)', '140 (54)', '0.1', '[q]'], ['78', 'United Kingdom', '244,376 (94,354)', '242,741 (93,723)', '1,635 (631)', '0.7', '[at]'], ['79', 'Uganda', '241,550 (93,263)', '200,520 (77,421)', '41,030 (15,840)', '17.0', ''], ['80', 'Ghana', '238,537 (92,100)', '227,533 (87,851)', '11,000 (4,200)', '4.6', ''], ['81', 'Romania', '238,398 (92,046)', '230,080 (88,834)', '8,320 (3,210)', '3.5', ''], ['82', 'Laos', '236,800 (91,430)', '230,800 (89,110)', '6,000 (2,000)', '2.5', '[au]'], ['83', 'Guyana', '214,969 (83,000)', '196,850 (76,004)', '18,120 (6,996)', '8.4', ''], ['84', 'Belarus', '207,600 (80,160)', '202,900 (78,340)', '4,700 (1,800)', '2.3', '[av]'], ['85', 'Kyrgyzstan', '199,949 (77,201)', '191,800 (74,050)', '8,150 (3,150)', '4.1', ''], ['86', 'Senegal', '196,712 (75,951)', '192,530 (74,336)', '4,180 (1,610)', '2.1', ''], ['87', 'Syria', '185,180 (71,498)', '183,630 (70,900)', '1,550 (598)', '0.8', '[aw]'], ['88', 'Cambodia', '181,035 (69,898)', '176,520 (68,155)', '4,520 (1,750)', '2.5', ''], ['–', 'Somaliland', '177,000 (68,300)', '', '', '', '[ax]'], ['89', 'Uruguay', '176,215 (68,037)', '175,015 (67,574)', '1,200 (460)', '0.7', ''], ['90', 'Suriname', '163,820 (63,251)', '156,000 (60,200)', '7,820 (3,020)', '4.8', '[ay]'], ['91', 'Tunisia', '163,610 (63,170)', '155,360 (59,985)', '8,250 (3,190)', '5.0', ''], ['92', 'Bangladesh', '148,460 (57,321)', '130,170 (50,259)', '18,290 (7,062)', '12.3', '[az]'], ['93', 'Nepal', '147,181 (56,827)', '143,350 (55,348)', '3,830 (1,480)', '2.6', '[ba]'], ['94', 'Tajikistan', '144,100 (55,640)', '141,510 (54,637)', '2,590 (1,000)', '1.8', ''], ['95', 'Greece', '131,957 (50,949)', '128,900 (49,770)', '1,310 (506)', '2.3', ''], ['96', 'Nicaragua', '130,373 (50,337)', '120,340 (46,464)', '10,030 (3,873)', '7.7', '[bb]'], ['97', 'North Korea', '120,538 (46,540)', '120,410 (46,491)', '130 (50)', '0.1', '[bc]'], ['98', 'Malawi', '118,484 (45,747)', '94,080 (36,320)', '24,404 (9,422)', '20.6', '[bd]'], ['99', 'Eritrea', '117,600 (45,410)', '101,000 (39,000)', '16,600 (6,410)', '14.1', '[be]'], ['100', 'Benin', '114,763 (44,310)', '112,760 (43,537)', '2,000 (800)', '1.7', ''], ['101', 'Honduras', '112,492 (43,433)', '111,890 (43,201)', '600 (200)', '0.5', ''], ['102', 'Liberia', '111,369 (43,000)', '96,320 (37,190)', '15,049 (5,810)', '13.5', '[q]'], ['103', 'Bulgaria', '110,879 (42,811)', '108,489 (41,888)', '2,390 (923)', '2.2', '[bf]'], ['104', 'Cuba', '109,884 (42,426)', '103,800 (40,080)', '6,080 (2,350)', '5.5', '[bg]'], ['105', 'Guatemala', '108,889 (42,042)', '107,160 (41,375)', '1,730 (668)', '1.6', ''], ['106', 'Iceland', '103,000 (39,800)', '100,830 (38,931)', '2,170 (838)', '2.1', ''], ['107', 'South Korea', '100,432 (38,777)', '97,600 (37,700)', '2,800 (1,100)', '2.8', '[bh]'], ['108', 'Hungary', '93,025 (35,917)', '91,260 (35,240)', '1,770 (683)', '1.9', ''], ['109', 'Portugal', '92,225 (35,608)', '91,606 (35,369)', '620 (240)', '0.7', ''], ['110', 'Jordan', '89,318 (34,486)', '88,794 (34,284)', '524 (202)', '0.6', ''], ['111', 'Serbia', '88,499 (34,170)', '88,499 (34,170)', '0', '0', '[bi]'], ['112', 'Azerbaijan', '86,600 (33,400)', '82,650 (31,910)', '3,950 (1,530)', '4.6', '[bj]'], ['113', 'Austria', '83,878 (32,385)', '82,520 (31,860)', '1,359 (525)', '1.6', ''], ['114', 'United Arab Emirates', '83,600 (32,300)', '82,880 (32,000)', '720 (280)', '0.9', '[bk]'], ['115', 'Czech Republic', '78,871 (30,452)', '77,187 (29,802)', '1,684 (650)', '2.1', ''], ['116', 'Panama', '75,320 (29,080)', '74,180 (28,640)', '1,143 (441)', '1.5', ''], ['117', 'Sierra Leone', '72,300 (27,900)', '72,180 (27,870)', '120 (46)', '0.2', ''], ['118', 'Ireland', '70,273 (27,133)', '68,883 (26,596)', '1,390 (537)', '2.0', '[bl]'], ['119', 'Georgia', '69,700 (26,900)', '69,490 (26,830)', '210 (81)', '0.3', '[bm]'], ['120', 'Sri Lanka', '65,610 (25,330)', '61,860 (23,880)', '3,750 (1,450)', '5.7', ''], ['121', 'Lithuania', '65,286 (25,207)', '62,610 (24,170)', '2,680 (1,040)', '4.1', ''], ['122', 'Latvia', '64,594 (24,940)', '62,230 (24,030)', '2,370 (915)', '3.7', ''], ['–', 'Svalbard (Norway)', '62,045 (23,956)', '62,045 (23,956)', '0', '0', '[bn]'], ['123', 'Togo', '56,785 (21,925)', '54,390 (21,000)', '2,400 (930)', '4.2', ''], ['124', 'Croatia', '56,594 (21,851)', '55,974 (21,612)', '620 (240)', '1.1', '[q]'], ['125', 'Bosnia and Herzegovina', '51,209 (19,772)', '51,200 (19,800)', '10 (4)', '0.0', ''], ['126', 'Costa Rica', '51,100 (19,700)', '51,060 (19,710)', '40 (20)', '0.1', ''], ['127', 'Slovakia', '49,035 (18,933)', '48,080 (18,560)', '950 (370)', '1.9', ''], ['128', 'Dominican Republic', '48,670 (18,790)', '48,320 (18,660)', '350 (140)', '0.7', ''], ['129', 'Estonia', '45,339 (17,505)', '42,388 (16,366)', '2,840 (1,100)', '6.3', ''], ['130', 'Denmark', '42,947 (16,582)', '42,434 (16,384)', '660 (260)', '1.5', '[bo]'], ['131', 'Netherlands', '41,865 (16,164)', '33,893 (13,086)', '7,650 (2,950)', '19.0', '[bp]'], ['132', 'Switzerland', '41,291 (15,943)', '39,510 (15,260)', '1,781 (688)', '4.3', ''], ['133', 'Bhutan', '38,394 (14,824)', '38,140 (14,730)', '250 (97)', '0.7', ''], ['134', 'Guinea-Bissau', '36,125 (13,948)', '28,120 (10,860)', '8,010 (3,090)', '22.2', ''], ['–', 'Taiwan', '35,980 (13,890)', '32,260 (12,460)', '3,720 (1,440)', '10.3', '[bq]'], ['135', 'Moldova', '33,847 (13,068)', '32,970 (12,730)', '880 (340)', '2.6', '[br]'], ['136', 'Belgium', '30,528 (11,787)', '30,280 (11,690)', '250 (97)', '0.8', ''], ['137', 'Lesotho', '30,355 (11,720)', '30,355 (11,720)', '0', '0', ''], ['138', 'Armenia', '29,743 (11,484)', '28,470 (10,990)', '1,270 (490)', '4.3', ''], ['139', 'Solomon Islands', '28,896 (11,157)', '27,990 (10,810)', '910 (350)', '3.1', ''], ['140', 'Albania', '28,748 (11,100)', '27,400 (10,600)', '330 (130)', '1.1', ''], ['141', 'Equatorial Guinea', '28,051 (10,831)', '28,051 (10,831)', '0', '0', ''], ['142', 'Burundi', '27,834 (10,747)', '25,680 (9,915)', '2,150 (830)', '7.7', ''], ['143', 'Haiti', '27,750 (10,710)', '27,560 (10,640)', '190 (73)', '0.7', ''], ['144', 'Rwanda', '26,338 (10,169)', '24,670 (9,525)', '1,670 (645)', '6.3', ''], ['145', 'North Macedonia', '25,713 (9,928)', '25,220 (9,737)', '490 (190)', '1.9', ''], ['146', 'Djibouti', '23,200 (8,960)', '23,180 (8,950)', '20 (8)', '0.1', '[q]'], ['147', 'Belize', '22,965 (8,867)', '22,810 (8,807)', '160 (62)', '0.7', ''], ['148', 'Israel', '21,937 (8,470)', '21,497 (8,300)', '440 (170)', '2.1', '[bs]'], ['149', 'El Salvador', '21,041 (8,124)', '20,720 (8,000)', '320 (120)', '1.5', '[bt]'], ['150', 'Slovenia', '20,273 (7,827)', '20,151 (7,780)', '122 (47)', '0.6', '[q]'], ['–', 'New Caledonia (France)', '18,575 (7,172)', '18,275 (7,056)', '300 (100)', '1.6', '[q]'], ['151', 'Fiji', '18,272 (7,055)', '18,272 (7,055)', '0', '0', ''], ['152', 'Kuwait', '17,818 (6,880)', '17,818 (6,880)', '0', '0', ''], ['153', 'Eswatini', '17,363 (6,704)', '17,200 (6,640)', '160 (62)', '0.9', ''], ['154', 'East Timor', '14,874 (5,743)', '14,874 (5,743)', '0', '0', '[q]'], ['155', 'Bahamas', '13,880 (5,359)', '10,010 (3,865)', '3,870 (1,490)', '27.8', ''], ['156', 'Montenegro', '13,812 (5,333)', '13,452 (5,194)', '360 (140)', '2.6', ''], ['157', 'Vanuatu', '12,189 (4,706)', '12,189 (4,706)', '0', '0', ''], ['–', 'Falkland Islands (UK)', '12,173 (4,700)', '12,173 (4,700)', '0', '0', ''], ['158', 'Qatar', '11,586 (4,473)', '11,586 (4,473)', '0', '0', '[q]'], ['159', 'Gambia', '11,295 (4,361)', '10,120 (3,907)', '1,180 (456)', '10.4', '[bu]'], ['160', 'Jamaica', '10,991 (4,244)', '10,830 (4,181)', '160 (62)', '1.5', ''], ['–', 'Kosovo', '10,887 (4,203)', '10,887 (4,203)', '0', '0', '[q]'], ['161', 'Lebanon', '10,452 (4,036)', '10,230 (3,950)', '220 (85)', '2.1', ''], ['162', 'Cyprus', '9,251 (3,572)', '9,241 (3,568)', '10 (4)', '0.1', '[bv]'], ['–', 'Puerto Rico (US)', '9,100 (3,500)', '8,868 (3,424)', '232 (89)', '2.5', '[37]'], ['–', 'Abkhazia', '8,665 (3,346)', '', '', '', '[bw]'], ['–', 'French Southern Territories (France)', '7,747 (2,991)', '7,668 (2,961)', '80 (30)', '1.0', '[bx]'], ['163', 'Palestine', '6,020 (2,320)', '6,025 (2,326)', '0', '0', '[by]'], ['164', 'Brunei', '5,765 (2,226)', '5,270 (2,040)', '500 (200)', '8.7', ''], ['165', 'Trinidad and Tobago', '5,127 (1,980)', '5,127 (1,980)', '0', '0', ''], ['–', 'French Polynesia (France)', '4,167 (1,609)', '3,827 (1,478)', '340 (130)', '8.2', '[q]'], ['–', 'Transnistria', '4,163 (1,607)', '', '', '', '[bz]'], ['166', 'Cape Verde', '4,033 (1,557)', '4,033 (1,557)', '0', '0', ''], ['–', 'South Georgia and the South Sandwich Islands (UK)', '3,903 (1,507)', '3,903 (1,507)', '0', '0', '[q]'], ['–', 'South Ossetia', '3,900 (1,500)', '', '', '', '[ca]'], ['–', 'Northern Cyprus', '3,355 (1,295)', '', '', '', '[cb]'], ['167', 'Samoa', '2,842 (1,097)', '2,780 (1,070)', '10 (4)', '0.4', ''], ['168', 'Luxembourg', '2,586 (998)', '2,574 (994)', '16 (6)', '0.6', ''], ['–', 'Bir Tawil (terra nullius)', '2,060 (795)', '2,060 (795)', '0', '0', ''], ['169', 'Mauritius', '2,040 (788)', '2,030 (784)', '10 (4)', '0.5', '[cc]'], ['170', 'Comoros', '1,861 (719)', '1,861 (719)', '0', '0', '[cd]'], ['–', 'Åland (Finland)', '1,581 (610)', '1,553 (600)', '28 (11)', '1.8', '[ce]'], ['–', 'Faroe Islands (Denmark)', '1,393 (538)', '1,393 (538)', '0', '0', '[q]'], ['–', 'Hong Kong (China)', '1,114 (430)', '1,050 (405)', '60 (20)', '5.4', '[cf]'], ['171', 'São Tomé and Príncipe', '964 (372)', '964 (372)', '0', '0', ''], ['–', 'Turks and Caicos Islands (UK)', '948 (366)', '948 (366)', '0', '0', ''], ['172', 'Kiribati', '811 (313)', '811 (313)', '0', '0', '[cg]'], ['173', 'Bahrain', '778 (300)', '778 (300)', '0', '0', '[ch]'], ['174', 'Dominica', '750 (290)', '750 (290)', '0', '0', ''], ['175', 'Tonga', '747 (288)', '720 (280)', '30 (10)', '4.0', ''], ['176', 'Singapore', '736 (284)', '726 (280)', '10 (4)', '1.4', '[ci]'], ['177', 'Micronesia', '702 (271)', '700 (270)', '0', '0', ''], ['178', 'Saint Lucia', '616 (238)', '610 (240)', '10 (4)', '1.6', ''], ['–', 'Isle of Man (UK)', '572 (221)', '570 (220)', '0', '0', ''], ['–', 'Guam (US)', '541 (209)', '540 (210)', '0', '0', ''], ['179', 'Andorra', '468 (181)', '468 (181)', '0', '0', '[cj]'], ['180', 'Palau', '459 (177)', '459 (177)', '0', '0', ''], ['–', 'Northern Mariana Islands (US)', '457 (176)', '457 (176)', '0', '0', ''], ['181', 'Seychelles', '457 (176)', '457 (176)', '0', '0', '[ck]'], ['–', 'Curaçao (Netherlands)', '444 (171)', '444 (171)', '0', '0', '[cl]'], ['182', 'Antigua and Barbuda', '442 (171)', '442 (171)', '0', '0', ''], ['183', 'Barbados', '431 (166)', '431 (166)', '0', '0', ''], ['–', 'Heard Island and McDonald Islands (Australia)', '412 (159)', '412 (159)', '0', '0', '[q]'], ['–', 'Saint Helena, Ascension and Tristan da Cunha (UK)', '394 (152)', '394 (152)', '0', '0', '[cm]'], ['184', 'Saint Vincent and the Grenadines', '389 (150)', '389 (150)', '0', '0', ''], ['–', 'Jan Mayen (Norway)', '377 (146)', '377 (146)', '0', '0', '[q]'], ['–', 'U.S. Virgin Islands (US)', '347 (134)', '347 (134)', '0', '0', ''], ['185', 'Grenada', '345 (133)', '340 (130)', '0', '0', ''], ['186', 'Malta', '315 (122)', '315 (122)', '0', '0', '[cn]'], ['187', 'Maldives', '300 (116)', '300 (116)', '0', '0', '[co]'], ['–', 'Bonaire (Netherlands)', '288 (111)', '288 (111)', '0', '0', '[cl]'], ['–', 'Cayman Islands (UK)', '264 (102)', '240 (93)', '24 (9)', '9.1', ''], ['188', 'Saint Kitts and Nevis', '261 (101)', '261 (101)', '0', '0', '[cp]'], ['–', 'Niue', '260 (100)', '260 (100)', '0', '0', '[cq]'], ['–', 'Akrotiri and Dhekelia (UK)', '254 (98)', '', '', '', '[cr]'], ['–', 'Saint Pierre and Miquelon (France)', '242 (93)', '230 (89)', '10 (4)', '4.2', ''], ['–', 'Cook Islands', '236 (91)', '236 (91)', '0', '0', '[cs]'], ['–', 'American Samoa (US)', '199 (77)', '199 (77)', '0', '0', ''], ['189', 'Marshall Islands', '181 (70)', '180 (69)', '0', '0', ''], ['–', 'Aruba (Netherlands)', '180 (69)', '180 (69)', '0', '0', '[cl]'], ['–', 'Easter Island (Chile)', '163 (63)', '163 (63)', '0', '0', '[ct]'], ['190', 'Liechtenstein', '160 (62)', '160 (62)', '0', '0', '[cu]'], ['–', 'British Virgin Islands (UK)', '151 (58)', '151 (58)', '0', '0', ''], ['–', 'Wallis and Futuna (France)', '142 (55)', '142 (55)', '0', '0', ''], ['–', 'Christmas Is

In [105]:
df2 = pd.DataFrame(rows2, columns=headers2)
df2

,,Country / dependency,Totalin km2 (mi2),Landin km2 (mi2),Waterin km2 (mi2),%water,
0,–,Earth,"510,072,000 (196,940,000)","148,940,000 (57,506,000)","361,132,000 (139,434,000)",70.8,
1,1,Russia,"17,098,246 (6,601,667)","16,376,870 (6,323,142)","721,380 (278,530)",4.2,[b]
2,–,Antarctica,"14,200,000 (5,480,000)","14,200,000 (5,480,000)",0,0,[c]
3,2,Canada,"9,984,670 (3,855,100)","9,093,507 (3,511,021)","891,163 (344,080)",8.9,[d]
4,3/4[e],China,"9,596,960 (3,705,410)","9,326,410 (3,600,950)","270,550 (104,460)",2.8,[f]
...,...,...,...,...,...,...,...
259,–,Ashmore and Cartier Islands (Australia),5.0 (1.9),5.0 (1.9),0,0,[q]
260,–,Coral Sea Islands (Australia),3.0 (1.2),3.0 (1.2),0,0,[db]
261,–,Spratly Islands (disputed),2.0 (0.77),2.0 (0.77),0,0,[55]
262,194,Monaco,2.0 (0.77),2.0 (0.77),0,0,[dc]
263,195,Vatican City,0.49 (0.19),0.49 (0.19),0,0,[dd]

In [106]:
df2.to_csv('countries_population2.csv', index=False)
print("Data saved to 'countries_population.csv'")

Data saved to 'countries_population.csv'

In [112]:
merged_df = pd.merge(df, df2, left_on='Country or territory', right_on='Country / dependency', how='inner')
merged_df.to_csv('merged_countries_population.csv', index=False)
print("Merged CSV saved as 'merged_countries_population.csv'")

Merged CSV saved as 'merged_countries_population.csv'